//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace sttp {

public enum MeasurementStateFlags : uint {
  Normal = 0,
  BadData = 1,
  SuspectData = 2,
  OverRangeError = 4,
  UnderRangeError = 8,
  AlarmHigh = 16,
  AlarmLow = 32,
  WarningHigh = 64,
  WarningLow = 128,
  FlatlineAlarm = 256,
  ComparisonAlarm = 512,
  ROCAlarm = 1024,
  ReceivedAsBad = 2048,
  CalculatedValue = 4096,
  CalculationError = 8192,
  CalculationWarning = 16384,
  ReservedQualityFlag = 32768,
  BadTime = 65536,
  SuspectTime = 131072,
  LateTimeAlarm = 262144,
  FutureTimeAlarm = 524288,
  UpSampled = 1048576,
  DownSampled = 2097152,
  DiscardedValue = 4194304,
  ReservedTimeFlag = 8388608,
  UserDefinedFlag1 = 16777216,
  UserDefinedFlag2 = 33554432,
  UserDefinedFlag3 = 67108864,
  UserDefinedFlag4 = 134217728,
  UserDefinedFlag5 = 268435456,
  SystemError = 536870912,
  SystemWarning = 1073741824,
  MeasurementError = 2147483648
}

}
