//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace sttp {

public enum MeasurementStateFlags : uint {
  Normal = 0x0,
  BadData = 0x1,
  SuspectData = 0x2,
  OverRangeError = 0x4,
  UnderRangeError = 0x8,
  AlarmHigh = 0x10,
  AlarmLow = 0x20,
  WarningHigh = 0x40,
  WarningLow = 0x80,
  FlatlineAlarm = 0x100,
  ComparisonAlarm = 0x200,
  ROCAlarm = 0x400,
  ReceivedAsBad = 0x800,
  CalculatedValue = 0x1000,
  CalculationError = 0x2000,
  CalculationWarning = 0x4000,
  ReservedQualityFlag = 0x8000,
  BadTime = 0x10000,
  SuspectTime = 0x20000,
  LateTimeAlarm = 0x40000,
  FutureTimeAlarm = 0x80000,
  UpSampled = 0x100000,
  DownSampled = 0x200000,
  DiscardedValue = 0x400000,
  ReservedTimeFlag = 0x800000,
  UserDefinedFlag1 = 0x1000000,
  UserDefinedFlag2 = 0x2000000,
  UserDefinedFlag3 = 0x4000000,
  UserDefinedFlag4 = 0x8000000,
  UserDefinedFlag5 = 0x10000000,
  SystemError = 0x20000000,
  SystemWarning = 0x40000000,
  MeasurementError = 0x80000000
}

}
