//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace sttp {

public enum SignalKind : ushort {
  Angle,
  Magnitude,
  Frequency,
  DfDt,
  Status,
  Digital,
  Analog,
  Calculation,
  Statistic,
  Alarm,
  Quality,
  Unknown
}

}
