<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0;net9.0;net6.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>x64;x86</Platforms>
    <Platform Condition="'$(Platform)' == '' Or '$(Platform)' == 'AnyCPU'">x64</Platform>
    <PlatformTarget>$(Platform)</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../lib/sttp.net/sttp.net.csproj" AdditionalProperties="Platform=$(Platform);GeneratePackageOnBuild=false" />
    <None Include="../../../build/output/$(Platform)/$(Configuration)/lib/sttp.net.lib.dll" Link="sttp.net.lib.dll" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
